config/routes.rb
Rails3test::Application.routes.draw do

  get "smokes/new"

  match '/help',  :to => 'static_pages#help'
  match '/about', :to => 'static_pages#about'
  match '/contact', :to => 'static_pages#contact'

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :wolves,   :only => [:create, :destroy, :index, :show]
  resources :smokes

  root :to => 'static_pages#home'

  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy', :via => :delete
  match '/events', :to => 'wolves#index'

end

app/models/smoke.rb
class Smoke < ActiveRecord::Base
  attr_accessible :parent_user_id, :user_id, :wolf_id
  
  belongs_to :user, :class_name => "User"
  belongs_to :wolf, :class_name => "Wolf"

  before_save :create_url_token
 
  validates :user_id, :presence => true,
                      :uniqueness => { :scope => :wolf_id }
  validates :wolf_id, :presence => true

  default_scope :order => 'smokes.created_at DESC'

  private
    def create_url_token
      self.url_token = SecureRandom.hex(16)
    end

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name, :password, :password_confirmation
  has_secure_password
  has_many :wolves, :dependent => :destroy
  has_many :smokes, :foreign_key => "user_id", :dependent => :destroy
  has_many :smoked_wolves, :through => :smokes, :source => :wolf_id

  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token

  validates :name, :presence => true, :length => { :maximum => 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, :presence => true, 
                    :format => { :with => VALID_EMAIL_REGEX },
                    :uniqueness => { :case_sensitive => false }
  validates :password, :presence => true,
                       :length => { :minimum => 6}
  validates :password_confirmation, :presence => true

  def smoked?(wolf)
    smokes.find_by_user_id_and_wolf_id(self.id, wolf.id)
  end

  def smoke!(wolf)
    smokes.create!(:wolf_id => wolf.id)
  end

  private
    def create_remember_token
      self.remember_token = SecureRandom.hex
    end

end

app/models/wolf.rb
class Wolf < ActiveRecord::Base
  attr_accessible :content
  belongs_to :user
  has_many :smokes, :foreign_key => "wolf_id", :dependent => :destroy
  has_many :smokers, :through => :smokes, :source => :user_id
  
  validates :content, :presence => true, :length => { :maximum => 140 }
  validates :user_id, :presence => true

  default_scope :order => 'wolves.created_at DESC'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
    user = User.find_by_email(params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      # Sign the user in and redirect to the user's show page.
      sign_in user
      redirect_back_or user
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end
  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/smokes_controller.rb
class SmokesController < ApplicationController
  before_filter :signed_in_user  

  def new
  end

  def create
    @smoke = Smoke.new(params[:smoke])
    @smoke.save!
    redirect_to @smoke.wolf
#    if @smoke.save
#      flash[:sucess] = "Event Spreaded!"
#    else
#    end
#    @wolf = @smoke.wolf
#    respond_to do |format|
#      format.html { redirect_to @smoke.wolf }
#      format.js
#    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @skip_footer = true
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user, :only => [:index, :edit, :update]  
  before_filter :correct_user,   :only => [:edit, :update]
  before_filter :admin_user,     :only => :destroy

  # GET /users
  # GET /users.json
  def index
    @users = User.paginate(:page => params[:page])
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    @wolves = @user.wolves.paginate(:page => params[:page])
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      flash[:success] = "Profile updated"
      sign_in @user
      redirect_to @user
    else
      render 'edit'
    end
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      flash[:success] = "Welcom to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to users_url
  end

  private
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end
    def admin_user
      redirect_to(root_path) unless current_user.admin?
    end
end

app/controllers/wolves_controller.rb
class WolvesController < ApplicationController
  before_filter :signed_in_user, :only => [:new, :create, :edit, :destroy]

  def new
  end

  def create
    @wolf = current_user.wolves.build(params[:wolf])
    if @wolf.save
      # add root smoke
      @smoke = Smoke.create(:user_id => current_user.id, :wolf_id =>@wolf.id, :parent_user_id => current_user.id)
      flash[:success] = "Event created!"
      redirect_to @wolf
    else
      render 'static_page/home'
    end
  end
 
  def edit
  end
  
  def destroy
  end
  
  def index
    @wolf = current_user.wolves.build if signed_in?
    @wolves = Wolf.paginate(:page => params[:page])
  end

  def show
    @wolf = Wolf.find(params[:id])
    @smokes = @wolf.smokes.paginate(:page => params[:page])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end
  
  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end

  def current_user?(user)
    user == current_user
  end

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, :notice => "Please sign in."
    end
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url
  end

end

app/helpers/smokes_helper.rb
module SmokesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = { :size => 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, :alt => user.name, :class => "gravatar")
  end
end

app/helpers/wolves_helper.rb
module WolvesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://railstutorial.org/">Rails Tutorial</a>
    by Michael Hartl
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "sample app", root_path, :id => "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home",    root_path %></li>
          <li><%= link_to "Events",  events_path %></li>
          <li><%= link_to "Help",    help_path %></li>
          <% if signed_in? %>
            <li><%= link_to "Users", users_path %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, :method => "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= stylesheet_link_tag    "application", :media=> "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>    
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' unless @skip_footer %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_smoke_form.html.erb
<%= form_for(current_user.smokes.build(:user_id => current_user.id, :wolf_id => @wolf.id, :parent_user_id => smoke.user_id)) do |f| %>
  <div>
    <%= f.hidden_field :user_id %>
    <%= f.hidden_field :wolf_id %>
    <%= f.hidden_field :parent_user_id %>
  </div>
  <%= f.submit "Spread", :class => "btn btn-large btn-primary" %>
<% end %>

app/views/smokes/_smoke.html.erb
<li>
    <span>
      <%= User.find(smoke.user_id).name %> 
      spreaded from <%= User.find(smoke.parent_user_id).name %>
    </span>
    <span class="timestamp">
        <%= time_ago_in_words(smoke.created_at) %> ago.
    </span>
    <span>
        url_token: <%= smoke.url_token %>
    </span>
    <% if signed_in? && !current_user.smoked?(smoke.wolf) %>
      <%= render 'shared/smoke_form', :smoke => smoke %>
    <% end %>
</li>

app/views/smokes/new.html.erb
<h1>Smokes#new</h1>
<p>Find me in app/views/smokes/new.html.erb</p>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>About Us</h1>
<p>
  The <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
  is a project to make a book and screencasts to teach web development
  with <a href="http://rubyonrails.org/">Ruby on Rails</a>. This
  is the sample application for the tutorial.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact Ruby on Rails Tutorial about the sample app at the
  <a href="http://railstutorial.org/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="http://railstutorial.org/help">Rails Tutorial help page</a>.
  To get help on this sample app, see the
  <a href="http://railstutorial.org/book">Rails Tutorial book</a>.
</p>

app/views/static_pages/home.html.erb
<div class="front-welcome-text">
  <h1>Welcome to Sample App</h1>
  <p>
    This is the home page for the
    <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
    sample application.
  </p>

  <%= link_to "Sign up now!", signup_path, :class => "btn btn-large btn-primary" %>
</div>

<div id="bg">
  <img src="http://www.cs.duke.edu/~msirivia/dandelion/dandelion.jpeg" alt="">
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_form_new.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Confirmation" %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, :size => 52 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, :method => :delete,
                                  :data => { :confirm => "You sure?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %> 
<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', :object => f.object %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Save changes", :class => "btn btn-large btn-primary" %>
    <% end %>

    <%= gravatar_for(@user) %>
    <a href="http://gravatar.com/emails">change</a>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', :object => f.object %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", :class => "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<h1>
  <%= gravatar_for @user %>
  <%= @user.name %>
  <% if @user.admin? %>
    <%= "(admin)" %> 
  <% end %>
</h1>

app/views/wolves/_wolf.html.erb
<li>
  <span class="name"><%= User.find(wolf.user_id).name %></span>
  <span class="content"><%= wolf.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(wolf.created_at) %> ago.
  </span>
  <%= link_to "detail", wolf %> 
</li>

app/views/wolves/_wolf_form.html.erb
<%= form_for(@wolf) do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.text_area :content, :placeholder => "Compose new event..." %>
  </div>
  <%= f.submit "Post", :class => "btn btn-large btn-primary" %>
<% end %>

app/views/wolves/index.html.erb
<% provide(:title, 'All events') %>
<h1>All events</h1>

<% if signed_in? %>
  <%= render 'wolf_form' %>
<% end %>

<%= will_paginate %>

<ul class="wolves">
  <%= render @wolves %>
</ul>

<%= will_paginate %>

app/views/wolves/new.html.erb
<h1>Wolves#new</h1>
<p>Find me in app/views/wolves/new.html.erb</p>

app/views/wolves/show.html.erb
<% provide(:title, @wolf.content) %>
<h1>Event Detail</h1>
<span class="content"><%= @wolf.content %></span>
<span>Posted by <%= User.find(@wolf.user_id).name %></span>
<span><%= time_ago_in_words(@wolf.created_at) %> ago.</span>
<span>spreaded 
  <strong id="spread_count" class="stat">
    <%= @wolf.smokes.count %> times.
  </strong>
</span>
<h1>Spreads</h1>
<ol class="smokes">
  <%= render @wolf.smokes %>
</ol>
<%= will_paginate @smokes %>